name: Compile protobuf stubs

on:
  push:
    branches: [master]

jobs:
  # This workflow contains a single job called "compile"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Install dependencies
    steps:
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - uses: bufbuild/buf-setup-action@v0.6.0

      - uses: arduino/setup-protoc@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: buf generate
      
      - name: Documentation
        run: make doc

      - name: Commit generated stubs
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add generated
          git add docs
          git commit -m "Automated: Update protobuf stubs"
          git push
