name: Push protos to BSR (Buf Schema Registry)

on:
  push:
    branches: [v1]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup build.buf
        uses: bufbuild/buf-setup-action@v1.1.0
        with:
          version: 1.1.0

      - name: Lint protos
        run: make proto-lint

      - uses: bufbuild/buf-push-action@v1        
        with:          
          input: api-spec/protobuf
          buf_token: ${{ secrets.BUF_TOKEN }}
